### ISSUE TITLE
unstable build failed

### ISSUE THREAD

**Issue by nutjob4life** [NASA-PDS/registry-crawler-service#26]
@tloubrieu-jpl commented on [Tue Dec 13 2022](https://github.com/NASA-PDS/roundup-action/issues/103)

## 🐛 Describe the bug

See action https://github.com/NASA-PDS/registry-crawler-service/actions/runs/3687311354

The snapshot release is done and accessible but on different url, see https://github.com/NASA-PDS/registry-crawler-service/releases/download/untagged-066a2eae3757652aed44/registry-crawler-service-1.1.0-SNAPSHOT-bin.tar.gz compared to what roundup is looking for, see https://github.com/NASA-PDS/registry-crawler-service/releases/download/v1.1.0-SNAPSHOT/registry-crawler-service-1.1.0-SNAPSHOT-bin.tar.gz

---

@nutjob4life commented on [Wed Dec 21 2022](https://github.com/NASA-PDS/roundup-action/issues/103#issuecomment-1362147768)

The workflow that had the problem wasn't a Roundup Action workflow, though. It was the Imaging workflow. I believe to fix this in `registry-crawler-api` we need [a fix similar to this one](https://github.com/NASA-PDS/registry-api/pull/205/files).

**Comment by tloubrieu-jpl** [comment]
Thanks @nutjob4life , so this ticket should be in the to do swim lane on the board ? the update of the github action is not done yet ?

**Comment by nutjob4life** [comment]
Hi @tloubrieu-jpl! This ticket should be in the "Review/QA" swim-lane as there's a [PR](https://github.com/NASA-PDS/registry-crawler-service/pull/27) for it awaiting review.

**Comment by tloubrieu-jpl** [comment]
Perfect, now it is closed !
